### ISSUE TITLE
HEAD requests enabled with `wisp.handle_head` do not set `Content-Length`

### ISSUE THREAD

**Issue by mna** [gleam-wisp/wisp#107]
Hello,

First of all thanks so much for Gleam and the awesome ecosystem of packages, toolings, documentation, etc. everything is top-notch and it's been nothing but fun diving into this language for me the past few weeks.

I started building a small web server to learn the ropes a bit, and I noticed that `wisp.handle_head` removes the `Content-Length` header from the response, which is unfortunate as it's probably the most useful information that one can get out of a `HEAD` request (outside of the status code I guess). Documentation on MDN does use this use-case as first example: https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD. My guess is that it's because a `set_body(Empty)` is used, and somewhere down the response pipeline that sets the Content-Length header?

I tested this with `curl -i --head http://localhost:8080/page`. I'm running wisp 1.3.0.

Thanks,
Martin

**Comment by lpil** [comment]
Wisp never sets a content length, it is set by the web server. I presume we'd need to replicate the web servers' content length calculation before we remove the body.

@rawhat Looking at Mist it doesn't set the content length for HEAD requests at all. Was this for a particular reason? I couldn't immediately see how content-length was calculate for send-file, though that is another matter.

Does Mist send a response body if one is provided for HEAD requests?

**Comment by rawhat** [comment]
Honestly, I don't remember why it's stripping content length for HEAD requests.  I think that was just a mistake.  I'll update that.  It also doesn't strip the response body, which is also incorrect.

Hopefully should have some time to update this in the near future.

**Comment by lpil** [comment]
Ah ok, that sounds like it would make things a lot easier from Wisp's point of view. We could return the body for HEAD and Mist would calculate the content length and then discard the body. Does that sound right?

**Comment by rawhat** [comment]
Yep that sounds good to me!

**Comment by lpil** [comment]
Amazing! Thank you

**Comment by rawhat** [comment]
This should hopefully be fixed in `mist` now 🤞🏻

**Comment by lpil** [comment]
Thank you!
