### ISSUE TITLE
Release 0.8.1 with updated simplifile.

### ISSUE THREAD

**Issue by hayleigh-dot-dev** [gleam-wisp/wisp#52]
I can see that recently the simplifile version constraint in `gleam.toml` was updated to `~> 1.0` in line with their latest major version release, but the latest published version of wisp still has the constraint `~> 0.3`.

This causes problems for folks that want to use wisp alongside _other_ packages that depend on simplifile (like lustre_ssg). This could be bumped in wisp as a patch change without any of the package's behaviour.

---

Context from #general in the [discord](https://discord.com/channels/768594524158427167/768594524158427170/1195755162782941194):

> I think I'm running into some dependency weirdness trying to add both wisp and lustre_ssg to the same project. The latest versions of both depend on simplifile 1.0, yet:
> - if I add wisp first, the manifest shows simplifile resolving to 0.4, which then makes adding lustre_ssg resolve to 0.2
> - if I add lustre_ssg first, the manifest shows simplifile resolving to 1.0, but then adding wisp resolves to version 0.1

**Comment by lpil** [comment]
Done!
