### ISSUE TITLE
Disable sasl logging by default

### ISSUE THREAD

**Issue by lpil** [gleam-wisp/wisp#56]

**Comment by markholmes** [comment]
I'm assuming the issue here is that `wisp.configure_logger` doesn't take a log level but is instead hard-coded as `Info`. What's the correct path here moving forward? Can we introduce breaking changes for `configure_logger` so that it accepts the `log_level`?

**Comment by markholmes** [comment]
I've gone down a bit of a rabbit hole here and don't fully understand what to do. I think that Elixir is building up filters to pass to the erlang logger via that `translate` function. I think what we would need to do is build a filter using [`logger:add_primary_filter()`](https://www.erlang.org/doc/man/logger#add_primary_filter-2) that listens for a `sasl` message type and filters it out. I'm assuming that's what the translate filter is doing in its function head:

```elixir
def translator(%{meta: %{domain: [:otp, :sasl | _]}}, %{sasl: false}), do: :stop
```

If you know of a better way to do this let me know 🙏
