### ISSUE TITLE
broken links to wisp github examples on hexdocs 

### ISSUE THREAD

**Issue by duckRabbitPy** [gleam-wisp/wisp#59]
The links on [hexdocs](https://hexdocs.pm/wisp/) to the wisp github examples are broken atm for me. 

It looks like prior to this commit https://github.com/gleam-wisp/wisp/commit/7414fc2e30baef40d0898cc46a71f53996f388c0 the github example folder names did not have leading 0s but now they do.

Hexdoc link
https://github.com/gleam-wisp/wisp/tree/main/examples/1-routing

vs

Actual route
https://github.com/gleam-wisp/wisp/tree/main/examples/01-routing

(As of Sat 2 March 2024)

**To reproduce:**

1. Go to hexdocs https://hexdocs.pm/wisp/
2. Click on any of the following links:

[Hello, World!](https://github.com/lpil/wisp/tree/main/examples/0-hello-world)
[Routing](https://github.com/lpil/wisp/tree/main/examples/1-routing)
[Working with form data](https://github.com/lpil/wisp/tree/main/examples/2-working-with-form-data)
[Working with JSON](https://github.com/lpil/wisp/tree/main/examples/3-working-with-json)
[Working with other formats](https://github.com/lpil/wisp/tree/main/examples/4-working-with-other-formats)
[Using a database](https://github.com/lpil/wisp/tree/main/examples/5-using-a-database)
[Serving static assets](https://github.com/lpil/wisp/tree/main/examples/6-serving-static-assets)
[Logging](https://github.com/lpil/wisp/tree/main/examples/7-logging)
[Working with cookies](https://github.com/lpil/wisp/tree/main/examples/8-working-with-cookies)
[Configuring default responses](https://github.com/lpil/wisp/tree/main/examples/9-configuring-default-responses)

3. Receive 404 on Github

**Comment by lpil** [comment]
Thank you! I've updated the docs

**Comment by DNEAVES** [comment]
Addition to this: "Working with Files" now points to a 404.

Reason: Link outputs "<examples url>/09-working-with-files"
Fix: Replace link to "<examples url>/10-working-with-files"
