### ISSUE TITLE
Failure opening tar archive

### ISSUE THREAD

**Issue by aiwaki** [gleam-wisp/wisp#65]
This error does not occur with other packages:
```
PS D:\Projects\gleam\my_project> gleam add wisp 
  Resolving versions
Downloading packages
error: Failure opening tar archive

There was a problem when attempting to expand a to a tar archive.    

This was error from the tar library:

    Unable to locate Hex package contents.tar.gz
```
Or just run `gleam run` in any of the [examples](https://github.com/gleam-wisp/wisp/tree/main/examples) to get the same error.

So far, I've only tried restarting my computer and reinstalling Gleam, but it hasn't helped.

**Comment by lpil** [comment]
Hello! Could you share more information on your setup please. Looks like Powershell- is that windows then? What file system are you using?

Could you share the output of `gleam build` with the `GLEAM_LOG=trace` environment variable set please. Thank you

**Comment by lpil** [comment]
Hello! This is unrelated to Wisp, could you open it in the Gleam repo please and include information on your system (OS, filesystem, etc) as well as the output with the `GLEAM_LOG` environment variable set to `trace`. Thank you
