### ISSUE TITLE
Cannot use anything but wisp v0.1.0

### ISSUE THREAD

**Issue by Faeq-F** [gleam-wisp/wisp#88]
I am completely new to gleam & wisp. I was trying to follow an article to setup my project for a web app. I did the following:
`
gleam new app
`
then
`
gleam add wisp lustre mist gleam_http gleam_erlang dot_env gleam_json
`

I then followed the article until I had to do  `import wisp.{type Request, type Response}` in router.gleam.
This resulted in the following:
```
  Compiling app

error: Unknown module field

  ┌─ C:\dev\FYP\app\src\app\router.gleam:3:14
  │
3 │ import wisp.{Request, Response}
  │              ^^^^^^^ Did you mean `main`?

The module `wisp` does not have a `Request` value.

error: Unknown module field
  ┌─ C:\dev\FYP\app\src\app\router.gleam:3:23
  │
3 │ import wisp.{Request, Response}
  │                       ^^^^^^^^ Did you mean `main`?

The module `wisp` does not have a `Response` value.

error: Unknown type
  ┌─ C:\dev\FYP\app\src\app\router.gleam:5:28
  │
5 │ pub fn handle_request(req: Request, ctx: Context) -> Response {
  │                            ^^^^^^^

The type `Request` is not defined or imported in this module.
```

I finally realized I was on version 0.1.0 but cannot get a higher version. `gleam update` doesn't do anything, running 
```
gleam add wisp

  Resolving versions
      Added wisp v0.1.0
```

doesn't help and if I specify a version I get something like the following:
```
gleam add wisp@0.16.0
  Resolving versions
error: Dependency resolution failed

An error occurred while determining what dependency packages and
versions should be downloaded.
The error from the version resolver library was:

Unable to find compatible versions for the version constraints in your
gleam.toml. The conflicting packages are:

- app
- gleam_json
- wisp
```

This is the gleam.toml I am now trying to use:
```
name = "app"
version = "1.0.0"

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"
wisp = ">= 0.1.0 and < 1.0.0"
gleam_erlang = ">= 0.25.0 and < 1.0.0"
mist = ">= 1.2.0 and < 2.0.0"
dot_env = ">= 1.1.0 and < 2.0.0"
lustre = ">= 4.3.0 and < 5.0.0"
gleam_json = ">= 2.0.0 and < 3.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"

```

I don't know if I am just making a simple mistake or doing something completely wrong but I can't seem to get a version other than 0.1.0

**Comment by Faeq-F** [comment]
to quickly add, my gleam.toml was
```
[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"
wisp = "~> 0.14"
gleam_erlang = "~> 0.25"
mist = "~> 1.0"
dot_env = "~> 0.5"
lustre = "~> 4.1"
gleam_json = ">= 1.0.0 and < 2.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
```

but then it changes to what I previously commented when I run gleam add

**Comment by lpil** [comment]
For some reasons I've not determined the instructions in that guide no longer work. I believe this may be due to one of the packages being out of date and conflicting with the others. Add them individually with Wisp first and see how that goes.

**Comment by lpil** [comment]
Wisp doesn't support gleam_json v2, you'll need to use the v1 line.

**Comment by Faeq-F** [comment]
Thank you!
