### ISSUE TITLE
BUG: Wisp Logger also logs info from different packages

### ISSUE THREAD

**Issue by baraich** [gleam-wisp/wisp#90]
Hi, I am creating an application and to store data in have chosen NeonDB. I have configured the environment variables are able to connect to the database. I have also configured the `wisp.configure_logger()` to log information regarding the given request.

## Background
To create a connection pool I have gone with official gleam (pgo) package.
```gleam
pub fn connect() {
  // Reading the DB connection URI from the environment.
  use pg_dbname <- result.try(env.get_string("DB_NAME"))
  use pg_host <- result.try(env.get_string("DB_HOST"))
  use pg_user <- result.try(env.get_string("DB_USER"))
  use pg_pass <- result.try(env.get_string("DB_PASS"))

  // Starting a connection pool
  Ok(
    pgo.Config(
      ..pgo.default_config(),
      ssl: True,
      host: pg_host,
      user: pg_user,
      pool_size: 25,
      database: pg_dbname,
      password: option.Some(pg_pass),
      connection_parameters: [#("sslmode", "verify-full")],
    )
    |> pgo.connect,
  )
}
```

The created connection pool is then used inside entry file
```gleam
// Getting the database connection pool
let assert Ok(db) = db.connect()
```

## Bug
The wisp logger prints details that is should print, but also logs out unnecessary information such as follows
```
Listening on http://localhost:8000               #OK
INFO 200 GET /                                   #OK
INFO reason=SslNotStarted at=Connecting          #Why log out info for gleam/pgo package?
INFO reason=SslNotStarted at=Connecting
INFO reason=SslNotStarted at=Connecting
```

## Expected Behaviour
```
Listening on http://localhost:8000         
INFO 200 GET /                                  
```

**Comment by baraich** [comment]
One workaround that I found was I implement by own function that used gleam instead of erlang to log the imcoming request.

```gleam
fn log_request(req: Request, handler: fn() -> Response) -> Response {
  let response = handler()

  [
    ansi.blue("INFO "),
    int.to_string(response.status),
    " ",
    string.uppercase(http.method_to_string(req.method)),
    " ",
    req.path,
  ]
  |> string.concat
  |> io.println

  response
}
```

## Usage
```gleam
// use <- wisp.log_request(request)
use <- log_request(request) 
```

## Doubts
Are there problems with the following approach, did the wisp logger solved some issues using erlangs logger?
Is this even method even good?

**Comment by lpil** [comment]
Hello!

This is not a bug. The Erlang `pgo` package is logging and it is being handled by Erlang like any other log message.

> did the wisp logger solved some issues using erlangs logger?

There is no Wisp logger, only the Erlang logger.

> One workaround that I found was I implement by own function that used gleam instead of erlang to log the imcoming request.

This is not using a logger, it is instead printing to stdout using the stdlib. This isn't recommended as you lose all the features the logger offers and it can easily have a large negative impact on performance.

**Comment by baraich** [comment]
Thanks @lpil!
I am new to learning gleam and go not have any background with erlang. There are also too few resources available, you need to look at the package docs only. I am still figuring out that why I am unable to connection to database at NeonDB using gleam/pgo?

**Comment by lpil** [comment]
What happens when you try and connect?

**Comment by baraich** [comment]
I have changed the database from NeonDB (postgresql) to Railway and that works fine! I am also able to access the data inside the database as well.
Thanks
