### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by rulanugrh** [gleam-wisp/wisp#95]
I have followed [example-routing](https://github.com/gleam-wisp/wisp/tree/main/examples/01-routing), but I get an error that results like this

![image](https://github.com/user-attachments/assets/7e9b7310-1a3c-49fb-9587-d8c6fc82a4ea)

For the dependencies that I use, I have followed them exactly as in the example.
![image](https://github.com/user-attachments/assets/2ccb741a-5505-460b-8cdc-8f11ca75f50a)

Can anyone help me? I think I have followed the steps given. 🤔

**Comment by lpil** [comment]
You're getting an Erlang error from calling an undefined function, which shouldn't be possible in Gleam.

Is your code available somewhere for me to look at?

**Comment by rulanugrh** [comment]
@lpil my code is like this, yeah actually I followed the example you gave [here](https://github.com/gleam-wisp/wisp/tree/main/examples/01-routing)

![image](https://github.com/user-attachments/assets/652e63fb-b381-4db9-baaf-aebec8db4bc6)
![image](https://github.com/user-attachments/assets/fc92eb56-a43b-4195-9850-b58fd3874444)
![image](https://github.com/user-attachments/assets/2397c869-bced-40a5-be27-f244bc12964d)

**Comment by lpil** [comment]
What version of Erlang are you using?

**Comment by rulanugrh** [comment]
@lpil my erlang version like this
![image](https://github.com/user-attachments/assets/2a3994cb-fc3f-4152-8d78-bee44c17770b)

**Comment by lpil** [comment]
Ah yes, it's OTP25. Please upgrade to OTP26 or newer, thank you.

**Comment by rulanugrh** [comment]
@lpil okayyy, Thank you for the help

**Comment by lpil** [comment]
No problem!
